import React, { Fragment, useState } from 'react';
import './wikipedia.css'


export const Wikipedia = (props) =>{
    return (
        <Fragment>
        <div className="wikipedia">
    {/* <div className="wikipediaContainer"> */}
        <h1 style={{color: "black"}}>History of Anime</h1>
        <div className ='wiki-text-body'> Naruto kun - The authentic design masterpieces Anime (Japanese: アニメ, IPA: [aɲime] (About this soundlisten)) is hand-drawn and SASUKEEEE computer animation originating from Japan. In Japanese, anime, a term derived from the English word animation, describes all animated works, regardless of style or origin. Outside of Japan, anime refers specifically to animation produced in Japan, or to its common style, which has since been adopted by a minority of works produced in other countries.[1]

The earliest commercial Japanese animations date to 1917. A characteristic art style emerged in the 1960s with the works of cartoonist Osamu Tezuka and spread in following decades, developing a large domestic audience. Anime is distributed theatrically, through television broadcasts, directly to home media, and over the Internet. In addition to original works, anime are often adaptations of Japanese comics (manga), light novels, or video games. It is classified into numerous genres targeting various broad and niche audiences.

Anime is a diverse medium with distinctive production methods that have adapted in response to emergent technologies. It combines graphic art, characterization, cinematography, and other forms of imaginative and individualistic techniques.[2] Compared to Western animation, anime production generally focuses less on movement, and more on the detail of settings and use of "camera effects", such as panning, zooming, and angle shots.[2] Diverse art styles are used, and character proportions and features can be quite varied, with a common characteristic feature being large and emotive eyes.[3]

The anime industry consists of over 430 production companies, including major studios like Studio Ghibli, Sunrise, and Toei Animation. Since the 1980s, the medium has also seen international success with the rise of foreign dubbed and subtitled programming. As of 2016, Japanese anime accounted for 60% of the world's animated television Animation in Japan began in the early 20th century, when filmmakers started to experiment with techniques pioneered in France, Germany, the United States, and Russia.[10] A claim for the earliest Japanese animation is Katsudō Shashin (c. 1907),[14] a private work by an unknown creator.[15] In 1917, the first professional and publicly displayed works began to appear; animators such as Ōten Shimokawa, Seitarō Kitayama, and Jun'ichi Kōuchi (considered the "fathers of anime") produced numerous films, the oldest surviving of which is Kōuchi's Namakura Gatana.[16] Many early works were lost with the destruction of Shimokawa's warehouse in the 1923 Great Kantō earthquake.[17]

By the mid-1930s animation was well-established in Japan as an alternative format to the live-action industry. It suffered competition from foreign producers, such as Disney, and many animators, including Noburō Ōfuji and Yasuji Murata, continued to work with cheaper cutout animation rather than cel animation.[18] Other creators, including Kenzō Masaoka and Mitsuyo Seo, nevertheless made great strides in technique, benefiting from the patronage of the government, which employed animators to produce educational shorts and propaganda.[19] In 1940, the government dissolved several artists' organizations to form the Shin Nippon Mangaka Kyōkai.[a][20] The first talkie anime was Chikara to Onna no Yo no Naka (1933), a short film produced by Masaoka.[21][22] The first feature-length anime film was Momotaro: Sacred Sailors (1945), produced by Seo with a sponsorship from the Imperial Japanese Navy.[23]


Momotaro: Sacred Sailors (1945), the first feature-length anime film
The 1950s saw a proliferation of short, animated advertisements made in Japan for television broadcasting.[24] In the 1960s, manga artist and animator Osamu Tezuka adapted and simplified many Disney animation techniques to reduce costs and limit frame counts in his productions.[25] He originally intended these as temporary measures to allow him to produce material on a tight schedule with an inexperienced staff, though many of his limited animation practices would later come to define the medium's style.[26] Three Tales (1960) was the first anime film broadcast on television;[27] the first anime television series was Instant History (1961–64).[28] An early and influential success was Astro Boy (1963–66), a television series directed by Tezuka based on his manga of the same name. Many animators at Tezuka's Mushi Production would later establish major studios (such as Madhouse, Sunrise, and Pierrot).

The 1970s saw growth in the popularity of manga, many of which were later animated. Tezuka's work—and that of other pioneers in the field—inspired characteristics and genres that remain fundamental elements of anime today. The giant robot genre (also known as "mecha"), for instance, took shape under Tezuka, developed into the super robot genre under Go Nagai and others, and was revolutionized at the end of the decade by Yoshiyuki Tomino, who developed the real robot genre.[29] Robot anime series such as Gundam and Super Dimension Fortress Macross became instant classics in the 1980s, and the genre remained one of the most popular in the following decades.[30] The bubble economy of the 1980s spurred a new era of high-budget and experimental anime films, including Nausicaä of the Valley of the Wind (1984), Royal Space Force: The Wings of Honnêamise (1987), and Akira (1988).[31]

Neon Genesis Evangelion (1995), a television series produced by Gainax and directed by Hideaki Anno, began another era of experimental anime titles, such as Ghost in the Shell (1995) and Cowboy Bebop (1998). In the 1990s, anime also began attracting greater interest in Western countries; major international successes include Sailor Moon and Dragon Ball Z, both of which were dubbed into more than a dozen languages worldwide. In 2003, Spirited Away, a Studio Ghibli feature film directed by Hayao Miyazaki, won the Academy Award for Best Animated Feature at the 75th Academy Awards. It later became the highest-grossing anime film,[b] earning more than $355 million. Since the 2000s, an increased number of anime works have been adaptations of light novels and visual novels; successful examples include The Melancholy of Haruhi Suzumiya and Fate/stay night (both 2006).shows.[4]to ge dynamism with aggression to produce a cutting edge carbon fiber monocoque. The interior of the Aventador combines high-level technology and luxury equipment with premium-quality materials, skilfully crafted with the expertise characteristic of the finest Italian traditions. A supercar family that has already become a legend in its own right. Discover technical specifications, dimensions, performance, and the detailed features of all the new Lamborghini Aventador models.Each and every detail of the Aventador bears the hallmarks of the House of the Raging Bull. It is a true masterpiece of design that expresses dynamism and power, with the carbon-fiber monocoque the jewel in its crown. The interior combines high-level technology and luxury equipment, crafted by skilled artisans using </div>
    </div>

    </Fragment>
    )
}

export default Wikipedia;